// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKOcjQ1QtTHR6weHfXeRPjIIt3quJ7tY',
    appId: '1:1056458793645:web:7bcff8d9b6bdc790291c24',
    messagingSenderId: '1056458793645',
    projectId: 'geminisignaltest-57b01',
    authDomain: 'geminisignaltest-57b01.firebaseapp.com',
    storageBucket: 'geminisignaltest-57b01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nt77mOJifAVfFDMDDMDFAYFzcz_QHPg',
    appId: '1:1056458793645:android:41e4a84f58ec5ce7291c24',
    messagingSenderId: '1056458793645',
    projectId: 'geminisignaltest-57b01',
    storageBucket: 'geminisignaltest-57b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLbnuMU6UBnsucRX5KjjeHnpVwq0eyyQ',
    appId: '1:1056458793645:ios:1ba930d42f3b199a291c24',
    messagingSenderId: '1056458793645',
    projectId: 'geminisignaltest-57b01',
    storageBucket: 'geminisignaltest-57b01.firebasestorage.app',
    iosBundleId: 'com.example.geminisignalAdminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLbnuMU6UBnsucRX5KjjeHnpVwq0eyyQ',
    appId: '1:1056458793645:ios:1ba930d42f3b199a291c24',
    messagingSenderId: '1056458793645',
    projectId: 'geminisignaltest-57b01',
    storageBucket: 'geminisignaltest-57b01.firebasestorage.app',
    iosBundleId: 'com.example.geminisignalAdminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVKOcjQ1QtTHR6weHfXeRPjIIt3quJ7tY',
    appId: '1:1056458793645:web:ef6aa25f6efac562291c24',
    messagingSenderId: '1056458793645',
    projectId: 'geminisignaltest-57b01',
    authDomain: 'geminisignaltest-57b01.firebaseapp.com',
    storageBucket: 'geminisignaltest-57b01.firebasestorage.app',
  );

}